DROP TABLE IF EXISTS observations;
CREATE TABLE observations (
    ID SERIAL NOT NULL,
    wind_speed NUMERIC(5, 2),
    sys_sunset NUMERIC(11),
    sys_type INTEGER,
    sys_sunrise NUMERIC(11),
    sys_message NUMERIC(6, 4),
    sys_country CHAR(3),
    sys_id INTEGER,
    main_temp_min NUMERIC(4, 2),
    main_humidity NUMERIC(5, 3),
    main_temp_max NUMERIC(4, 2),
    main_pressure NUMERIC(6, 2),
    main_temp NUMERIC(4, 2),
    visibility NUMERIC(6, 2),
    name CHAR(20),
    coord_lon NUMERIC(5, 2),
    coord_lat NUMERIC(5, 2),
    clouds_all INTEGER,
    weather_main CHAR(36),
    weather_description CHAR(36),
    weather_id INTEGER,
    dt NUMERIC(11),
    PRIMARY KEY(ID)
);