# Best reg subset top 5
expl_vars <- list(winter = c('period_of_day','mean_24_wind_speed','min_24_temperature','mean_24_temperature'),
                  spring = c('period_of_day','day_of_year','min_24_pm2_5','mean_24_temperature'),
                  summer = c('pressure','day_of_year','max_24_pressure','mean_24_temperature'),
                  autumn = c('day_of_year','hour_of_day','mean_24_wind_speed','mean_24_humidity'))

# Best reg subset top 10
expl_vars <- list(winter = c('pm2_5','temperature','period_of_day','day_of_year','hour_of_day','mean_24_wind_speed','min_24_pressure','min_24_temperature','mean_24_temperature'),
                  spring = c('pressure','period_of_day','day_of_year','mean_24_pm2_5','max_24_pm2_5','mean_24_wind_speed','max_24_pressure','mean_24_temperature','max_24_temperature'),
                  summer = c('pressure','period_of_day','day_of_year','min_24_pm2_5','max_24_pressure','min_24_temperature','mean_24_temperature','max_24_temperature','mean_24_wind_dir_ns'),
                  autumn = c('wind_speed','temperature','day_of_year','hour_of_day','mean_24_pressure','max_24_pressure','min_24_temperature','mean_24_temperature','max_24_wind_dir_ns'))

# Best reg subset top 15
expl_vars <- list(winter = c('pm2_5','wind_speed','temperature','is_holiday','period_of_day','day_of_year', 'hour_of_day','max_24_wind_speed','min_24_pressure','min_24_humidity','min_24_temperature', 'mean_24_temperature','max_24_temperature','mean_24_wind_dir_ns'),
                  spring = c('pressure','period_of_day','is_heating_season','day_of_year','mean_24_pm2_5','max_24_pm2_5', 'mean_24_wind_speed','min_24_pressure','max_24_pressure','mean_24_humidity','max_24_humidity', 'mean_24_temperature','max_24_temperature','min_24_wind_dir_ew'),
                  summer = c('pressure','period_of_day','month','day_of_year','wind_dir_ew','min_24_pm2_5', 'max_24_wind_speed','max_24_pressure','min_24_temperature','mean_24_temperature', 'max_24_temperature','max_24_precip_rate','max_24_wind_dir_ew','mean_24_wind_dir_ns'),
                  autumn = c('wind_speed','temperature','humidity','pressure','is_holiday','day_of_year', 'hour_of_day','min_24_wind_speed','max_24_pressure','mean_24_humidity','min_24_temperature', 'mean_24_temperature','max_24_wind_dir_ew','mean_24_wind_dir_ns'))

# Best reg subset top 20
expl_vars <- list(winter = c('wind_speed','wind_dir_deg','solradiation','temperature','is_holiday','period_of_day','month','year','day_of_year','hour_of_day','wind_dir_ns','max_24_wind_speed','min_24_pressure','min_24_humidity','min_24_temperature','mean_24_temperature','max_24_temperature','max_24_wind_dir_ew','mean_24_wind_dir_ns'),
                  spring = c('wind_speed','temperature','pressure','period_of_day','is_heating_season','day_of_year','hour_of_day','min_24_pm2_5','mean_24_pm2_5','max_24_pm2_5','mean_24_wind_speed','min_24_pressure','max_24_pressure','min_24_humidity','mean_24_humidity','max_24_humidity','mean_24_temperature','max_24_temperature','min_24_wind_dir_ew'),
                  summer = c('precip_rate','solradiation','humidity','pressure','is_holiday','period_of_day','month','day_of_year','wind_dir_ew','min_24_pm2_5','max_24_wind_speed','max_24_pressure','mean_24_humidity','min_24_temperature','mean_24_temperature','max_24_temperature','max_24_precip_rate','max_24_wind_dir_ew','mean_24_wind_dir_ns'),
                  autumn = c('pm2_5','wind_speed','temperature','humidity','pressure','is_holiday','month','year','day_of_year','hour_of_day','min_24_wind_speed','max_24_wind_speed','mean_24_pressure','max_24_pressure','mean_24_humidity','max_24_humidity','min_24_temperature','mean_24_temperature','max_24_wind_dir_ew'))

# Variables selected by LASSO (abs(coefficients) > 1e-4)
expl_vars <- list(winter = c('pm2_5','wind_speed','wind_dir_deg','precip_total','precip_rate','solradiation','temperature','humidity','pressure','is_holiday','period_of_day','month','year','day_of_week','day_of_year','hour_of_day','wind_dir_ew','wind_dir_ns','min_24_pm2_5','mean_24_pm2_5','max_24_pm2_5','min_24_wind_speed','max_24_wind_speed','min_24_pressure','mean_24_pressure','max_24_pressure','min_24_humidity','mean_24_humidity','max_24_humidity','min_24_temperature','mean_24_temperature','max_24_temperature','min_24_precip_rate','mean_24_precip_rate','max_24_precip_rate','min_24_wind_dir_ew','mean_24_wind_dir_ew','max_24_wind_dir_ew','min_24_wind_dir_ns','mean_24_wind_dir_ns','max_24_wind_dir_ns'),
                  spring = c('pm2_5','wind_speed','wind_dir_deg','precip_total','precip_rate','solradiation','temperature','humidity','pressure','is_holiday','period_of_day','is_heating_season','month','year','day_of_week','day_of_year','hour_of_day','wind_dir_ew','wind_dir_ns','min_24_pm2_5','mean_24_pm2_5','max_24_pm2_5','min_24_wind_speed','mean_24_wind_speed','max_24_wind_speed','min_24_pressure','mean_24_pressure','max_24_pressure','min_24_humidity','mean_24_humidity','max_24_humidity','min_24_temperature','mean_24_temperature','max_24_temperature','min_24_precip_rate','max_24_precip_rate','min_24_wind_dir_ew','mean_24_wind_dir_ew','max_24_wind_dir_ew','min_24_wind_dir_ns','mean_24_wind_dir_ns','max_24_wind_dir_ns'),
                  summer = c('pm2_5','wind_speed','wind_dir_deg','precip_total','precip_rate','solradiation','temperature','humidity','pressure','is_holiday','period_of_day','is_heating_season','month','year','day_of_week','day_of_year','hour_of_day','wind_dir_ew','wind_dir_ns','min_24_pm2_5','mean_24_pm2_5','max_24_pm2_5','min_24_wind_speed','mean_24_wind_speed','max_24_wind_speed','mean_24_pressure','max_24_pressure','min_24_humidity','mean_24_humidity','max_24_humidity','min_24_temperature','mean_24_temperature','max_24_temperature','min_24_precip_rate','mean_24_precip_rate','max_24_precip_rate','min_24_wind_dir_ew','mean_24_wind_dir_ew','max_24_wind_dir_ew','min_24_wind_dir_ns','mean_24_wind_dir_ns','max_24_wind_dir_ns'),
                  autumn = c('pm2_5','wind_speed','wind_dir_deg','precip_total','precip_rate','solradiation','temperature','humidity','pressure','is_holiday','period_of_day','month','year','day_of_week','day_of_year','hour_of_day','wind_dir_ew','wind_dir_ns','min_24_pm2_5','mean_24_pm2_5','max_24_pm2_5','min_24_wind_speed','mean_24_wind_speed','max_24_wind_speed','min_24_pressure','mean_24_pressure','max_24_pressure','min_24_humidity','mean_24_humidity','max_24_humidity','min_24_temperature','mean_24_temperature','max_24_temperature','min_24_precip_rate','mean_24_precip_rate','max_24_precip_rate','min_24_wind_dir_ew','mean_24_wind_dir_ew','max_24_wind_dir_ew','min_24_wind_dir_ns','mean_24_wind_dir_ns','max_24_wind_dir_ns'))
