- split_type: season_and_year
  test_years:
  - 2018.0
  output_dir: results/test/
  stations:
  - gios_bulwarowa
  repetitions: 5.0
  models:
  - hidden: '15'
    activation: relu
    epochs: '100'
    min_delta: 1e-04
    patience_ratio: '0.25'
    batch_size: '32'
    learning_rate: '0.1'
    epsilon: 1e-08
    l2: '0.1'
    type: neural_network
    split_id: 1
  - hidden: 10-5
    activation: relu
    epochs: '100'
    min_delta: 1e-04
    patience_ratio: '0.25'
    batch_size: '32'
    learning_rate: '0.001'
    epsilon: 1e-05
    l2: '0.001'
    type: neural_network
    split_id: 2
  - hidden: '5'
    activation: relu
    epochs: '100'
    min_delta: 1e-04
    patience_ratio: '0.25'
    batch_size: '32'
    learning_rate: '0.01'
    epsilon: 1e-07
    l2: '1'
    type: neural_network
    split_id: 3
  - hidden: '10'
    activation: relu
    epochs: '100'
    min_delta: 1e-04
    patience_ratio: '0.25'
    batch_size: '32'
    learning_rate: '0.01'
    epsilon: 1e-07
    l2: '1'
    type: neural_network
    split_id: 4
