- split_type: year
  test_years: 
    - 2018
  stations:
    - gios_krasinskiego
  models:
    - type: neural
      activation: relu
      epochs: 100
      patience_ratio: 0.2
      min_delta: 1e-4
      hidden:
        - '5'
        - '10'
        - '15'
        - '5-3'
        - '10-5'
        - '10-5-3'
        - '20-10-5-3'
