- split_type: year
  test_years: [2017]
  stations:
    - gios_krasinskiego
  models:
    - type: neural
      stepmax: 1
      act_fun: tanh
      children:
      - hidden: '5'
        threshold: 0.75
      - hidden: '10'
        threshold: 1
      - hidden: '15'
        threshold: 1
      - hidden: '5-3'
        threshold: 3
      - hidden: '10-5'
        threshold: 8.5
      - hidden: '10-7'
        threshold: 5
      - hidden: '10-5-3'
        threshold: 2.5
