- split_type: year
  test_years: [2017]
  stations: [gios_krasinskiego]
  models:
    - type: svr
      random: true
      model_count: 10
      kernel: radial
      exp_base: 2
      exp_step: 2
      gamma:
        min: -12
        max: -4
      epsilon:
        min: -5
        max: 1
      cost:
        min: -2
        max: 10
