- split_type: year
  test_years:
  - 2018.0
  output_dir: results/test/
  stations:
  - gios_krasinskiego
  repetitions: 5.0
  models:
  - hidden: '10'
    activation: relu
    epochs: '100'
    min_delta: 1e-04
    patience_ratio: '0.25'
    batch_size: '32'
    learning_rate: 1e-04
    epsilon: 1e-06
    l2: '1'
    type: neural_network
  - hidden: 10-5
    activation: relu
    epochs: '100'
    min_delta: 1e-04
    patience_ratio: '0.25'
    batch_size: '32'
    learning_rate: '0.01'
    epsilon: 1e-06
    l2: '0.001'
    type: neural_network
  - hidden: 10-5
    activation: relu
    epochs: '100'
    min_delta: 1e-04
    patience_ratio: '0.25'
    batch_size: '32'
    learning_rate: '0.01'
    epsilon: 1e-06
    l2: '0.001'
    type: neural_network
  - hidden: '5'
    activation: relu
    epochs: '100'
    min_delta: 1e-04
    patience_ratio: '0.25'
    batch_size: '32'
    learning_rate: '0.01'
    epsilon: 1e-07
    l2: '1'
    type: neural_network
