- split_type: season_and_year
  test_years: [2017]
  stations: 
    - gios_bulwarowa
  models:
    - type: svr
      random: true
      kernel: radial
      children:
        - gamma: 0.015625
          epsilon: 0.5
          cost: 16.0
        - gamma: 0.015625
          epsilon: 2.0
          cost: 256.0
        - gamma: 0.015625
          epsilon: 0.125
          cost: 256.0
        - gamma: 0.0625
          epsilon: 0.125
          cost: 64.0
        - gamma: 0.0009766
          epsilon: 0.125
          cost: 1.0
        - gamma: 0.015625
          epsilon: 0.03125
          cost: 16.0
        - gamma: 0.0625
          epsilon: 2.0
          cost: 1.0
        - gamma: 0.0625
          epsilon: 0.5
          cost: 1.0
        - gamma: 0.0039062
          epsilon: 2.0
          cost: 1024.0
        - gamma: 0.0002441
          epsilon: 0.125
          cost: 0.25
        - gamma: 0.0039062
          epsilon: 0.125
          cost: 1.0
        - gamma: 0.0009766
          epsilon: 2.0
          cost: 16.0
        - gamma: 0.0002441
          epsilon: 0.5
          cost: 4.0
        - gamma: 0.015625
          epsilon: 0.5
          cost: 0.25
        - gamma: 0.0625
          epsilon: 0.5
          cost: 1024.0
        - gamma: 0.0625
          epsilon: 0.5
          cost: 64.0
        - gamma: 0.0039062
          epsilon: 0.125
          cost: 0.25
        - gamma: 0.0625
          epsilon: 0.03125
          cost: 0.25
        - gamma: 0.0009766
          epsilon: 0.5
          cost: 1024.0
        - gamma: 0.0625
          epsilon: 0.125
          cost: 256.0
        - gamma: 0.0625
          epsilon: 0.5
          cost: 16.0
        - gamma: 0.0002441
          epsilon: 2.0
          cost: 256.0
        - gamma: 0.0002441
          epsilon: 0.5
          cost: 256.0
        - gamma: 0.0039062
          epsilon: 0.125
          cost: 4.0
        - gamma: 0.0039062
          epsilon: 0.125
          cost: 256.0
        - gamma: 0.0002441
          epsilon: 2.0
          cost: 4.0
        - gamma: 0.0002441
          epsilon: 2.0
          cost: 16.0
        - gamma: 0.0002441
          epsilon: 0.5
          cost: 1024.0
        - gamma: 0.015625
          epsilon: 0.5
          cost: 1024.0
        - gamma: 0.0039062
          epsilon: 0.5
          cost: 64.0
        - gamma: 0.0039062
          epsilon: 0.03125
          cost: 16.0
        - gamma: 0.0625
          epsilon: 0.03125
          cost: 1024.0
        - gamma: 0.015625
          epsilon: 0.125
          cost: 1024.0
        - gamma: 0.015625
          epsilon: 2.0
          cost: 1024.0
        - gamma: 0.015625
          epsilon: 2.0
          cost: 4.0
        - gamma: 0.0009766
          epsilon: 2.0
          cost: 1.0
        - gamma: 0.015625
          epsilon: 0.125
          cost: 0.25
        - gamma: 0.0002441
          epsilon: 0.5
          cost: 64.0
        - gamma: 0.0625
          epsilon: 0.03125
          cost: 16.0
        - gamma: 0.0002441
          epsilon: 0.03125
          cost: 16.0
        - gamma: 0.0625
          epsilon: 0.125
          cost: 0.25
        - gamma: 0.015625
          epsilon: 0.125
          cost: 16.0
        - gamma: 0.0625
          epsilon: 2.0
          cost: 0.25
        - gamma: 0.0002441
          epsilon: 2.0
          cost: 0.25
        - gamma: 0.0009766
          epsilon: 2.0
          cost: 4.0
        - gamma: 0.0002441
          epsilon: 0.125
          cost: 1.0
        - gamma: 0.0625
          epsilon: 0.03125
          cost: 64.0
        - gamma: 0.0002441
          epsilon: 0.03125
          cost: 1.0
        - gamma: 0.0625
          epsilon: 0.03125
          cost: 256.0
        - gamma: 0.0039062
          epsilon: 2.0
          cost: 16.0
  
