- split_type: season_and_year
  repetitions: 5
  output_dir: results/validation/
  test_years: 
    - 2017
  stations:
    - gios_bujaka
    - gios_bulwarowa
    - gios_krasinskiego
  models:
    - type: neural
      activation: relu
      epochs: 100
      patience_ratio: 0.25
      min_delta: 1e-4
      hidden:
        - '5'
        - '10'
        - '15'
        - '5-3'
        - '10-5'
        - '10-5-3'
        - '20-10-5-3'

